DATASET:
  TRAIN_PATH: "./ufpr_dataset/training"
  TEST_PATH: "./ufpr_dataset/testing"
  IMAGE_FORMAT: ".png"

SAM:
  CHECKPOINT: "./sam_vit_b_01ec64.pth"
  RANK: 512

TRAIN:
  BATCH_SIZE: 1
  NUM_EPOCHS: 30
  LEARNING_RATE: 0.0001
  PATIENCE: 10
